name: Arduino Compile Check

on:
  push:
  pull_request:

permissions:
  contents: read
  attestations: write
  id-token: write

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Update index
        run: arduino-cli core update-index

      - name: Install Arduino core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Install Servo library
        run: |
          arduino-cli lib update-index
          arduino-cli lib install Servo

      - name: Compile sketch
        run: |
          arduino-cli compile \
            --fqbn arduino:avr:mega \
            --output-dir build \
            ./servosensorled

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: arduino-build
          path: build/

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: build/**